# ELEC 474 Prelab 
Matthieu Roux 20013052

In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread("baboon.png")
x = y = red = green = blue = 0

# segment_pixels will hold all the points that are in the region
segment_pixels = {}
# next_pixel_stack holds all the points that could be added to the segment.
next_pixel_stack=[]

In [3]:
segment_color = [0, 255, 0] # should be a very bright green

## onMouse
The `onMouse` function handles the left click trigger on the image and obtains the coordinates of the click

In [4]:
def onMouse(event,_x,_y,flags,param):
    global x, y, green, blue, red, img, next_pixel_stack
    if event == cv2.EVENT_LBUTTONDOWN:
        green = img[_y,_x,0]
        blue = img[_y,_x,1]
        red = img[_y,_x,2]
        x = _x
        y = _y
        
        next_pixel_stack.append((_y,_x))
        segmentation()
#         print('[', x, y, '] = ', green, blue, red)

In [5]:
def segmentation():
    global x, y, green, blue, red, img, next_pixel_stack, segment_pixels, segment_color
    og_pixel = img[next_pixel_stack[0]]
    print(og_pixel)
    while len(next_pixel_stack) > 0:
        pixel = next_pixel_stack.pop()
        # check if the pixels are already in the degment
        if pixel in segment_pixels:
            continue
        if is_homogeneous(og_pixel, img[pixel]):
            segment_pixels[pixel] = True
            # update the pixel
            img[pixel] = segment_color
            # find the next potential pixels and add them to the stack
            next_pixels = get_next_pixels(pixel)
            next_pixel_stack.extend(next_pixels)
            print(pixel)

In [6]:
threshold = 100
def get_diff(value1, value2):
    return abs(int(value1)-int(value2))
    
def is_homogeneous(og_pixel, pixel):
    homogeneous = get_diff(og_pixel[0],pixel[0]) <= threshold or get_diff(og_pixel[1],pixel[1]) <= threshold or get_diff(og_pixel[2],pixel[2]) <= threshold
x    return homogeneous

In [7]:
def get_next_pixels(pixel):
    global img
    max_x = img.shape[1]
    max_y = img.shape[0]
    next_pixels = []
    if pixel[0] != 0:
        next_pixels.append((pixel[0] - 1, pixel[1]))
    if pixel[0] != max_y:
        next_pixels.append((pixel[0] + 1, pixel[1]))
    if pixel[1] != 0:
        next_pixels.append((pixel[0], pixel[1] - 1))
    if pixel[1] != max_x:
        next_pixels.append((pixel[0], pixel[1] + 1))
    return next_pixels

In [8]:
cv2.namedWindow('image')


keepGoing = True 
while(keepGoing):
    cv2.setMouseCallback('image', onMouse)
    # Wait a little bit for the image to re-draw
    key = cv2.waitKey(1)
    cv2.imshow("image", img)
    if key == ord("x"):
        keepGoing = False
        

[212 199 203]
True
(259, 255)
True
(259, 256)
True
(259, 257)
True
(259, 258)
False
True
(260, 258)
True
(260, 259)
False
True
(261, 259)
True
(261, 260)
False
True
(262, 260)
True
(262, 261)
False
False
False
True
(262, 259)
True
(262, 258)
True
(262, 257)
False
True
(263, 257)
False
False
True
(264, 257)
True
(264, 258)
True
(264, 259)
True
(264, 260)
False
False
True
(263, 260)
False
True
(263, 259)
False
False
False
False
True
(264, 256)
True
(264, 255)
False
False
False
True
(265, 256)
True
(265, 257)
False
False
False
False
False
True
(261, 257)
True
(261, 258)
True
(261, 256)
True
(261, 255)
False
False
True
(260, 255)
True
(260, 256)
True
(260, 257)
True
(260, 254)
True
(260, 253)
True
(260, 252)
True
(260, 251)
True
(260, 250)
False
True
(261, 250)
True
(261, 251)
True
(261, 252)
True
(261, 253)
False
False
True
(262, 252)
False
True
(262, 251)
True
(262, 250)
True
(262, 249)
False
True
(263, 249)
True
(263, 250)
True
(263, 251)
True
(263, 252)
False
True
(264, 252)
False
True

IndexError: index 512 is out of bounds for axis 1 with size 512

[  0 255   0]
True
(220, 308)
True
(220, 309)
True
(220, 310)
True
(220, 311)
True
(220, 312)
True
(220, 313)
True
(220, 314)
True
(220, 315)
True
(220, 316)
True
(220, 317)
True
(220, 318)
True
(220, 319)
True
(220, 320)
True
(220, 321)
True
(220, 322)
True
(220, 323)
True
(220, 324)
True
(220, 325)
True
(220, 326)
True
(220, 327)
True
(220, 328)
True
(220, 329)
True
(220, 330)
True
(220, 331)
True
(220, 332)
True
(220, 333)
True
(220, 334)
True
(220, 335)
True
(220, 336)
True
(220, 337)
True
(220, 338)
True
(220, 339)
True
(220, 340)
True
(220, 341)
True
(220, 342)
True
(220, 343)
True
(220, 344)
True
(220, 345)
True
(220, 346)
True
(220, 347)
True
(220, 348)
True
(220, 349)
True
(220, 350)
True
(220, 351)
True
(220, 352)
True
(220, 353)
True
(220, 354)
True
(220, 355)
True
(220, 356)
True
(220, 357)
True
(220, 358)
True
(220, 359)
True
(220, 360)
True
(220, 361)
True
(220, 362)
True
(220, 363)
True
(220, 364)
True
(220, 365)
True
(220, 366)
True
(220, 367)
True
(220, 368)
True
(220,

IndexError: index 512 is out of bounds for axis 1 with size 512

[  0 255   0]
True
(350, 222)
True
(350, 223)
True
(350, 224)
True
(350, 225)
True
(350, 226)
True
(350, 227)
True
(350, 228)
True
(350, 229)
True
(350, 230)
True
(350, 231)
True
(350, 232)
True
(350, 233)
True
(350, 234)
True
(350, 235)
True
(350, 236)
True
(350, 237)
True
(350, 238)
False
True
(351, 238)
True
(351, 239)
True
(351, 240)
True
(351, 241)
True
(351, 242)
False
True
(352, 242)
False
True
(352, 241)
True
(352, 240)
False
True
(353, 240)
True
(353, 241)
False
True
(354, 241)
True
(354, 242)
True
(354, 243)
True
(354, 244)
True
(354, 245)
True
(354, 246)
True
(354, 247)
False
True
(355, 247)
True
(355, 248)
True
(355, 249)
True
(355, 250)
True
(355, 251)
True
(355, 252)
False
True
(356, 252)
True
(356, 253)
True
(356, 254)
True
(356, 255)
True
(356, 256)
True
(356, 257)
True
(356, 258)
True
(356, 259)
True
(356, 260)
True
(356, 261)
True
(356, 262)
True
(356, 263)
True
(356, 264)
True
(356, 265)
True
(356, 266)
True
(356, 267)
True
(356, 268)
True
(356, 269)
True
(356, 270)


IndexError: index 512 is out of bounds for axis 1 with size 512

[  0 255   0]
True
(328, 229)
True
(328, 230)
True
(328, 231)
True
(328, 232)
True
(328, 233)
True
(328, 234)
True
(328, 235)
True
(328, 236)
True
(328, 237)
True
(328, 238)
True
(328, 239)
True
(328, 240)
True
(328, 241)
True
(328, 242)
True
(328, 243)
True
(328, 244)
True
(328, 245)
True
(328, 246)
True
(328, 247)
True
(328, 248)
True
(328, 249)
True
(328, 250)
True
(328, 251)
True
(328, 252)
True
(328, 253)
True
(328, 254)
True
(328, 255)
True
(328, 256)
True
(328, 257)
True
(328, 258)
True
(328, 259)
True
(328, 260)
True
(328, 261)
True
(328, 262)
True
(328, 263)
True
(328, 264)
True
(328, 265)
True
(328, 266)
True
(328, 267)
True
(328, 268)
True
(328, 269)
True
(328, 270)
True
(328, 271)
True
(328, 272)
True
(328, 273)
True
(328, 274)
True
(328, 275)
True
(328, 276)
True
(328, 277)
True
(328, 278)
True
(328, 279)
False
True
(329, 279)
False
True
(329, 278)
True
(329, 277)
True
(329, 276)
True
(329, 275)
True
(329, 274)
True
(329, 273)
True
(329, 272)
True
(329, 271)
True
(329, 270

IndexError: index 512 is out of bounds for axis 0 with size 512

[  0 255   0]
True
(182, 263)
True
(182, 264)
True
(182, 265)
True
(182, 266)
True
(182, 267)
True
(182, 268)
True
(182, 269)
True
(182, 270)
True
(182, 271)
True
(182, 272)
True
(182, 273)
True
(182, 274)
True
(182, 275)
True
(182, 276)
True
(182, 277)
True
(182, 278)
True
(182, 279)
True
(182, 280)
True
(182, 281)
True
(182, 282)
True
(182, 283)
True
(182, 284)
True
(182, 285)
True
(182, 286)
False
True
(183, 286)
True
(183, 287)
False
False
False
False
True
(184, 286)
False
False
True
(185, 286)
False
False
True
(186, 286)
False
False
True
(187, 286)
False
True
(187, 285)
False
True
(188, 285)
True
(188, 286)
False
True
(189, 286)
False
True
(189, 285)
False
True
(190, 285)
True
(190, 286)
False
True
(191, 286)
False
False
True
(192, 286)
False
False
True
(193, 286)
False
False
True
(194, 286)
False
False
True
(195, 286)
False
False
True
(196, 286)
False
True
(196, 285)
False
False
False
True
(197, 286)
False
False
True
(198, 286)
False
False
True
(199, 286)
False
True
(199, 285)
Tr

IndexError: index 512 is out of bounds for axis 1 with size 512

[  0 255   0]
True
(133, 424)
True
(133, 425)
True
(133, 426)
True
(133, 427)
True
(133, 428)
True
(133, 429)
False
True
(134, 429)
True
(134, 430)
True
(134, 431)
True
(134, 432)
True
(134, 433)
True
(134, 434)
True
(134, 435)
True
(134, 436)
True
(134, 437)
True
(134, 438)
False
True
(135, 438)
True
(135, 439)
True
(135, 440)
True
(135, 441)
True
(135, 442)
True
(135, 443)
True
(135, 444)
True
(135, 445)
True
(135, 446)
True
(135, 447)
True
(135, 448)
False
True
(136, 448)
True
(136, 449)
True
(136, 450)
True
(136, 451)
True
(136, 452)
True
(136, 453)
True
(136, 454)
True
(136, 455)
True
(136, 456)
True
(136, 457)
True
(136, 458)
True
(136, 459)
True
(136, 460)
True
(136, 461)
True
(136, 462)
True
(136, 463)
False
True
(137, 463)
True
(137, 464)
True
(137, 465)
True
(137, 466)
True
(137, 467)
False
True
(138, 467)
True
(138, 468)
True
(138, 469)
True
(138, 470)
True
(138, 471)
True
(138, 472)
True
(138, 473)
True
(138, 474)
True
(138, 475)
True
(138, 476)
True
(138, 477)
True
(138, 4

IndexError: index 512 is out of bounds for axis 1 with size 512

[  0 255   0]
True
(97, 449)
True
(97, 450)
True
(97, 451)
True
(97, 452)
True
(97, 453)
True
(97, 454)
True
(97, 455)
True
(97, 456)
True
(97, 457)
True
(97, 458)
True
(97, 459)
True
(97, 460)
True
(97, 461)
True
(97, 462)
True
(97, 463)
True
(97, 464)
True
(97, 465)
True
(97, 466)
False
True
(98, 466)
False
True
(98, 465)
True
(98, 464)
True
(98, 463)
True
(98, 462)
True
(98, 461)
True
(98, 460)
True
(98, 459)
True
(98, 458)
True
(98, 457)
True
(98, 456)
True
(98, 455)
True
(98, 454)
True
(98, 453)
True
(98, 452)
True
(98, 451)
True
(98, 450)
True
(98, 449)
True
(98, 448)
True
(98, 447)
True
(98, 446)
True
(98, 445)
True
(98, 444)
True
(98, 443)
True
(98, 442)
True
(98, 441)
True
(98, 440)
True
(98, 439)
True
(98, 438)
True
(98, 437)
True
(98, 436)
True
(98, 435)
True
(98, 434)
False
True
(99, 434)
True
(99, 435)
True
(99, 436)
True
(99, 437)
True
(99, 438)
True
(99, 439)
True
(99, 440)
False
True
(100, 440)
True
(100, 441)
True
(100, 442)
True
(100, 443)
True
(100, 444)
True
(100, 4

IndexError: index 512 is out of bounds for axis 1 with size 512

[  0 255   0]
True
(178, 193)
True
(178, 194)
True
(178, 195)
True
(178, 196)
True
(178, 197)
True
(178, 198)
True
(178, 199)
True
(178, 200)
True
(178, 201)
True
(178, 202)
True
(178, 203)
True
(178, 204)
True
(178, 205)
True
(178, 206)
True
(178, 207)
True
(178, 208)
True
(178, 209)
True
(178, 210)
True
(178, 211)
False
True
(179, 211)
True
(179, 212)
True
(179, 213)
True
(179, 214)
True
(179, 215)
True
(179, 216)
True
(179, 217)
True
(179, 218)
True
(179, 219)
True
(179, 220)
True
(179, 221)
True
(179, 222)
False
False
True
(178, 222)
False
True
(178, 221)
True
(178, 220)
True
(178, 219)
True
(178, 218)
True
(178, 217)
False
True
(177, 217)
True
(177, 218)
True
(177, 219)
False
True
(176, 219)
True
(176, 220)
False
False
True
(175, 220)
False
True
(175, 219)
True
(175, 218)
True
(175, 217)
True
(175, 216)
True
(175, 215)
True
(175, 214)
True
(175, 213)
True
(175, 212)
True
(175, 211)
True
(175, 210)
True
(175, 209)
True
(175, 208)
True
(175, 207)
True
(175, 206)
True
(175, 205)
True

IndexError: index 512 is out of bounds for axis 1 with size 512

In [9]:
cv2.destroyAllWindows()